name: reaktoro

{% set python_version = os.environ.get("PYTHON_VERSION", "3.9") %}

channels:
  - conda-forge

dependencies:
  - autodiff
  - catch2
  - ccache  # [unix]
  - clangxx_osx-64  # [osx]
  - clcache  # [win]
  - cmake
  - cpp-tabulate
  - doxygen=1.8.20  # [linux]
  - eigen4rkt
  - fire
  - git
  - graphviz  # [linux]
  - gxx_linux-64  # [linux]
  - ninja
  - nlohmann_json
  - numpy
  - openlibm
  - optima
  - pandas
  - phreeqc4rkt
  - pip
  - pugixml
  - pybind11
  - pybind11-abi
  - pybind11-stubgen
  - pytest
  - pytest-regressions
  - pytest-xdist
  - python={{ python_version }}
  - thermofun==0.3.8
  - vs2019_win-64  # [win]
  - yaml-cpp4rkt
  - pip:
    - oyaml
