name: linux

on:
  push:
    branches:
      - master
      - v2.0-preview

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      os: Linux-x86_64
      configuration: Release

    strategy:
      fail-fast: true
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true

      - name: Configuring Conda Environment
        shell: bash -l {0}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda devenv
      - name: Configuring Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: $HOME/.ccache
          key: ${{ runner.os }}-ccache
      - name: Building, Testing & Installing Reaktoro
        shell: bash -l {0}
        run: |
          source activate reaktoro
          ccache -s
          ccache -z
          mkdir .build && cd .build
          cmake -GNinja .. -DCMAKE_BUILD_TYPE=${{ env.configuration }}
          ninja
          ninja tests
          ninja install
          ccache -s
