name: windows

on:
  push:
    branches:
      - master
      - v2.0-preview

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:

    runs-on: windows-latest

    env:
      configuration: Release

    strategy:
      fail-fast: true
      max-parallel: 4

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          auto-activate-base: true
          activate-environment: ''
      - name: Configuring Conda Environment
        shell: powershell
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda devenv
      - name: Configuring Cache
        id: cache
        uses: actions/cache@v2
        with:
          path: $HOME\clcache
          key: ${{ runner.os }}-clcache
      - name: Installing Dependencies
        shell: powershell
        run: |
          conda activate reaktoro
          cmake -P deps/install
      - name: Configuring Reaktoro
        shell: powershell
        run: |
          conda activate reaktoro
          set CC=clcache
          set CXX=clcache
          cmake -GNinja -S . -B .build -DCMAKE_BUILD_TYPE=${{ env.configuration }}
      - name: Building Reaktoro
        shell: powershell
        run: |
          conda activate reaktoro
          clcache -s
          clcache -z
          cmake --build .build --config ${{ env.configuration }}
          clcache -s
      - name: Installing Reaktoro
        shell: powershell
        run: |
          conda activate reaktoro
          cmake --build .build --config ${{ env.configuration }} --target install
      - name: Testing Reaktoro
        shell: powershell
        run: |
          conda activate reaktoro
          cmake --build .build --config ${{ env.configuration }} --target tests
