name: windows

on:
  push:
    branches:
      - master
      - v2.0-preview

  pull_request:

  schedule:
    - cron: "0 5 * * 1"  # runs at 05:00 UTC on Mondays

jobs:
  build:
    name: ${{ matrix.config }} build on ${{ matrix.os }} (Python ${{ matrix.python-version }})
    runs-on: windows-latest

    strategy:
      fail-fast: true
      max-parallel: 4
      matrix:
        os: ["windows-latest"]
        python-version: [3.9]
        config: ["Release"]

    steps:
      - uses: actions/checkout@v2

      - name: Configuring Cache
        id: cache
        uses: actions/cache@v2
        env:
          cache-number: 0  # If build fails possibly because of cache, increase this number to create a new empty cache directory
        with:
          path: |
            C:\Users\runneradmin\clcache
            C:\Users\runneradmin\conda_pkgs_dir
          key: ${{ runner.os }}-${{ matrix.config }}-${{ runner.python-version }}-${{ github.ref }}-${{ env.cache-number }}-clcache

      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-activate-base: false
          allow-softlinks: true
          activate-environment: ''
          channels: conda-forge
          channel-priority: true
          use-only-tar-bz2: true  # IMPORTANT: This needs to be set true for caching of miniconda packages to work properly!

      - name: Configuring Conda Environment
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}
        run: |
          conda config --set always_yes yes --set changeps1 no
          conda config --add channels conda-forge
          conda install conda-devenv
          conda devenv

      - name: Building, Testing & Installing Reaktoro
        shell: cmd
        run: |
          call conda activate reaktoro || goto :eof
          clcache -s || goto :eof
          clcache -z || goto :eof
          mkdir .build && cd .build || goto :eof
          cmake -GNinja .. ^
              -DCMAKE_CXX_COMPILER=clcache ^
              -DCMAKE_BUILD_TYPE=${{ matrix.config }} || goto :eof
          ninja || goto :eof
          ninja install || goto :eof
          ninja tests || goto :eof
          clcache -s || goto :eof
